apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: expose-route
spec:
  steps:
    - name: expose-route
      image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202310131344.p0.g3470d04.assembly.stream
      command:
        - oc
      args:
        - create
        - route
        - edge
        - python-sample-app
        - --service=python-sample-app
        - --port=5000-tcp
        - --insecure-policy=Redirect
