apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-env-var
spec:
  steps:
    - name: set-env-var
      image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202310131344.p0.g3470d04.assembly.stream
      command:
        - oc
      args:
        - set
        - env
        - bc/python-sample-app
        - APP_FILE=helloworld.py
